name: hustl
channels:
  - conda-forge
  - pytorch
  - menpo
dependencies:
  - python=3.6.*
  - numpy=1.16.2
  - scipy=1.2.1
  - scikit-image=0.15.0
  - scikit-video=1.1.11
  - pillow=6.0.0
  - pytorch-cpu=1.0.1
  - torchvision-cpu=0.2.2
  - matplotlib=3.0.3
  - seaborn=0.9.0
  - jupyter=1.0.0
  - notebook=5.7.8
  - cyvlfeat=0.4.6
  - hub=2.11.2
  - pip>=18.1
  - pip:
    - rawpy==0.13.1
    - pyqt5==5.12.1